---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: src/home-content/1-cataloghi.md
  label: 1. Cataloghi
- type: document
  path: src/home-content/2-galleria.md
  label: 2. Galleria
- type: document
  path: src/home-content/3-opuscoli.md
  label: 3. Opuscoli
- type: document
  path: src/home-content/4-bibliografia.md
  label: 4. Bibliografia
- type: document
  path: src/about.md
  label: About
upload_dir: src/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
